"""outbox and tool_invocations

Revision ID: 9a705f3fc376
Revises: d03e998066fb
Create Date: 2026-08-28 12:52:26.969519
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "9a705f3fc376"
down_revision = "d03e998066fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbox_kind"), "outbox", ["kind"], unique=False)
    op.create_index(op.f("ix_outbox_task_id"), "outbox", ["task_id"], unique=False)
    op.create_table(
        "tool_invocations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("subtask_id", sa.String(length=16), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("args_hash", sa.String(length=32), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("result_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_invocations_decision"), "tool_invocations", ["decision"], unique=False
    )
    op.create_index(
        op.f("ix_tool_invocations_task_id"), "tool_invocations", ["task_id"], unique=False
    )
    op.create_index(op.f("ix_tool_invocations_tool"), "tool_invocations", ["tool"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_invocations_tool"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_task_id"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_decision"), table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_index(op.f("ix_outbox_task_id"), table_name="outbox")
    op.drop_index(op.f("ix_outbox_kind"), table_name="outbox")
    op.drop_table("outbox")
    # ### end Alembic commands ###
